# Generated by Django 3.0.2 on 2020-01-30 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whirlybird_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='PredictionPerHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('temperature', models.IntegerField()),
                ('precipitation', models.FloatField()),
                ('wind_force', models.IntegerField()),
                ('wind_direction', models.CharField(max_length=5)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whirlybird_backend.Icon')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whirlybird_backend.CableParks')),
            ],
        ),
        migrations.CreateModel(
            name='PredictionPerDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('min_temp', models.IntegerField()),
                ('max_temp', models.IntegerField()),
                ('precipitation', models.FloatField()),
                ('wind_force', models.IntegerField()),
                ('wind_direction', models.CharField(max_length=5)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whirlybird_backend.Icon')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whirlybird_backend.CableParks')),
            ],
        ),
    ]
